### ISSUE TITLE
Tutorial navigation going through footer

### ISSUE THREAD

**Issue by calgary34** [learnmonkey/learnmonkey.github.io#13]
The tutorial navigation is going though the footer. Also, line breaks won't help because the tutorial list will keep growing, thus going into the footer again. Any ideas of how it happened?

**Comment by MonkeyED** [comment]
`<br>` can help but it isn't a good fix, perhaps css margins?

**Comment by calgary34** [comment]
@MonkeyED Have you figured out what was wrong with the footer?

**Comment by MonkeyED** [comment]
no, but `<br>` does work so i feel like its the margins or something

**Comment by calgary34** [comment]
Margins? Hm. Might work. Let's try it.

**Comment by MonkeyED** [comment]
or its just how we goofed the includes things

**Comment by MonkeyED** [comment]
possibly...

**Comment by MonkeyED** [comment]
i've commited a margin test, but ill fix this issue!

**Comment by calgary34** [comment]
GitHub pages prob gonna take awhile

**Comment by calgary34** [comment]
Oh, and if the margins don't work, try padding

**Comment by calgary34** [comment]
Wait....the tutorial list was created using Bootstrap. What if we replaced the bootstrap list with an equivalent pure css list?

**Comment by calgary34** [comment]
Or is that too much work?

**Comment by calgary34** [comment]
thanks @MonkeyED !
