### ISSUE TITLE
More Tutorials

### ISSUE THREAD

**Issue by MonkeyED** [learnmonkey/learnmonkey.github.io#14]
Other than fixing the bugs oh the site, we also need more tutorials. What other ones should we make for Python/Html/css/Js??

**Comment by calgary34** [comment]
Hmm. Python tutorials are easy, we can work on those, as we are skilled in Python. I think we should we working on making the tutorials more readable and more accessible.

**Comment by calgary34** [comment]
Like we've done variables, the next logical step is functions and loops and data types, that kind of thing. We could of course use other tutorial websites as reference.

**Comment by MonkeyED** [comment]
yes, but well need numbers to like ` +`, `-`, `*`, `/`, `**`, etc

**Comment by calgary34** [comment]
We can add those as we go.

**Comment by ThePeeps191** [comment]
hehehe
