### ISSUE TITLE
Tutorial navigation going through footer: again!

### ISSUE THREAD

**Issue by calgary34** [learnmonkey/learnmonkey.github.io#16]
The tutorial navigation is going through the footer again. Turns out the margins were just a temporary solution.
![image](https://user-images.githubusercontent.com/51468959/148456460-b31e8e91-536f-4981-9f88-50f75de1b1c1.png)

**Comment by calgary34** [comment]
It's now a billion times worse:
![image](https://user-images.githubusercontent.com/51468959/148579637-0f84ed37-0f37-4739-a964-09fce92ab89d.png)

**Comment by ThePeeps191** [comment]
ok, ill fix it

**Comment by calgary34** [comment]
Good. Made a new pure CSS list group for the tutorials. It seems to be fixed.
