### ISSUE TITLE
Use HighlightJS instead of ToHTML.com

### ISSUE THREAD

**Issue by calgary34** [learnmonkey/learnmonkey.github.io#17]
HighlightJS has Go highlighting and doesn't make the code unreadable.

**Comment by calgary34** [comment]
HighlightJS works for Go! Now the only thing we have to do is to do it for all the other tutorials we have.

**Comment by ThePeeps191** [comment]
hm, im not sure how hightlightjs works so you start doing it

**Comment by calgary34** [comment]
It doesn't work anymore.....

**Comment by ThePeeps191** [comment]
fixed!!

**Comment by calgary34** [comment]
We still need to do it for the rest of the tutorials.....

**Comment by ThePeeps191** [comment]
whaaaaaaaaaaaaaaaaaa

**Comment by ThePeeps191** [comment]
lets just use hljs **FROM NOW ON** so we dont need to change the old stuff...

**Comment by calgary34** [comment]
I'm doing it now

**Comment by ThePeeps191** [comment]
ok

**Comment by calgary34** [comment]
I've done most of the migration to HighlightJS. The only thing that seems to be left is the Python functions page.

**Comment by calgary34** [comment]
@ThePeeps191 Nice! Now let me see if you finished the migration.....

**Comment by calgary34** [comment]
Good. Done.

**Comment by ThePeeps191** [comment]
👍
