### ISSUE TITLE
Navbar dropdown

### ISSUE THREAD

**Issue by calgary34** [learnmonkey/learnmonkey.github.io#18]
Now that we have math, could the programming stuff be merge into one dropdown and the math stuff in one dropdown like that? It sure would make things easier.

**Comment by ThePeeps191** [comment]
uuh sure

**Comment by ThePeeps191** [comment]
btw i figureed out that the problem is bootstrap... oooooof

**Comment by ThePeeps191** [comment]
done!
https://replit.com/@ThePeeps191/test-hover#style.css
https://test-hover.thepeeps191.repl.co

**Comment by ThePeeps191** [comment]
will integrate later...

**Comment by calgary34** [comment]
Fix it ASAP.
The botched navbar is destroying the entire site...

**Comment by calgary34** [comment]
It (mostly) works now!
