### ISSUE TITLE
Dark and Light Mode

### ISSUE THREAD

**Issue by calgary34** [learnmonkey/learnmonkey.github.io#19]
Perhaps there could be a switch in the navbar that could toggle between light and dark mode.

**Comment by ThePeeps191** [comment]
ok

**Comment by calgary34** [comment]
My idea is that there could be some kind of switch in the navbar and could toggle between light and dark mode.

**Comment by ThePeeps191** [comment]
done!

**Comment by calgary34** [comment]
@ThePeeps191 Could there be different HighlightJS themes for light and dark mode?

**Comment by ThePeeps191** [comment]
uh sure ill try to do that

**Comment by ThePeeps191** [comment]
i'll make a settings page or something later
