### ISSUE TITLE
Brown Theme

### ISSUE THREAD

**Issue by MonkeyED** [learnmonkey/learnmonkey.github.io#4]
The website shall have a brown theme, CSS needs to be updated, I'll do most of the work

**Comment by calgary34** [comment]
Sure, I'm currently working on the footer.

**Comment by calgary34** [comment]
Also, the brown I'm using for the footer is rgb(90, 63, 4). Do something different for the navbar, like maybe a little lighter or darker.

**Comment by calgary34** [comment]
Wait, the navbar looks maroon not brown

**Comment by calgary34** [comment]
Also, please use light gray for the navbar links just for consistency

**Comment by MonkeyED** [comment]
yes, the website now has a brown theme, works
