### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by calgary34** [learnmonkey/learnmonkey.github.io#7]
I think that the current navigation system is quite awkward because people have to scroll all the way down the page to find the links. @MonkeyED Could you make a sidebar? In particular, I think it should be scrollable, like the one on w3schools.

**Comment by MonkeyED** [comment]
I have made the navbar sticky, it should work fine now.

**Comment by calgary34** [comment]
I'm not talking about the navbar; I'm talking about the tutorial list at the end of the tutorials.

**Comment by calgary34** [comment]
I think that it should be a scrollable sidebar like the one found on w3schools.

**Comment by MonkeyED** [comment]
oh ok, ill start on that!!

**Comment by MonkeyED** [comment]
rip we screwed up on that >_<

**Comment by MonkeyED** [comment]
ooooooof

**Comment by calgary34** [comment]
Oh god
